name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  rust:
    name: cargo fmt & cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install -y libwayland-cursor0 libxkbcommon-dev libwayland-dev

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  example:
    name: wasm compile & deploy example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown

      - name: build example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example basic --release --target wasm32-unknown-unknown

      - name: create www dir
        run: |
          mkdir www
          cp target/wasm32-unknown-unknown/release/examples/basic/*.wasm www
          cp examples/*.html www

      - name: deploy to github pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
